import { useState } from 'react';
import jsPDF from 'jspdf';
import { NDADraftInput, LegalNoticeDraftInput } from '@/lib/drafter';

export function useDraft() {
  const [docType, setDocType] = useState<'NDA' | 'LEGAL_NOTICE'>('NDA');
  const [isDrafting, setIsDrafting] = useState(false);
  const [generatedDraft, setGeneratedDraft] = useState<string>('');
  const [copiedDraft, setCopiedDraft] = useState(false);
  const [draftError, setDraftError] = useState<string>('');

  const [ndaForm, setNdaForm] = useState<NDADraftInput>({
    disclosingParty: 'Acme Software Solutions Pvt Ltd',
    receivingParty: 'Bharat Tech Innovations LLP',
    effectiveDate: '2026-07-28',
    jurisdiction: 'New Delhi High Court',
    purpose: 'evaluating a strategic AI co-counsel integration and source code licensing',
    durationYears: 2,
    confidentialScope: 'proprietary ML models, customer databases, revenue metrics, and backend APIs',
    disputeResolution: 'Arbitration under New Delhi International Arbitration Centre (NDIAC)',
    tone: 'Formal'
  });

  const [noticeForm, setNoticeForm] = useState<LegalNoticeDraftInput>({
    claimantName: 'Adv. Suresh Verma on behalf of LexCorp India',
    respondentName: 'Apex Retail Enterprises India Pvt Ltd',
    noticeDate: '2026-07-28',
    causeOfAction: 'failure to settle unpaid invoices amounting to ₹ 8,50,000 for IT legal consultancy services',
    demandAmount: '₹ 8,50,000/- (Rupees Eight Lakhs Fifty Thousand Only)',
    curePeriodDays: 15,
    jurisdiction: 'District Court, Mumbai',
    tone: 'Assertive'
  });

  const handleGenerateDraft = async () => {
    setIsDrafting(true);
    setDraftError('');
    try {
      const inputs = docType === 'NDA' ? ndaForm : noticeForm;
      const res = await fetch('/api/draft', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ docType, inputs })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Draft generation failed');
      if (data.draftContent) {
        setGeneratedDraft(data.draftContent);
      }
    } catch (err: any) {
      setDraftError(err.message || 'Error generating document draft');
    } finally {
      setIsDrafting(false);
    }
  };

  const handleExportPDF = () => {
    if (!generatedDraft) return;
    const doc = new jsPDF();
    
    // Header
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(14);
    doc.text(docType === 'NDA' ? "NON-DISCLOSURE AGREEMENT" : "LEGAL DEMAND NOTICE", 20, 20);

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text("Generated by Lawxygen AI Co-Counsel Platform", 20, 26);
    doc.line(20, 29, 190, 29);

    // Body
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    const splitText = doc.splitTextToSize(generatedDraft, 170);
    let y = 36;

    for (let i = 0; i < splitText.length; i++) {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }
      doc.text(splitText[i], 20, y);
      y += 5;
    }

    doc.save(`${docType}_Legal_Draft_Lawxygen.pdf`);
  };

  const handleCopyDraft = () => {
    navigator.clipboard.writeText(generatedDraft);
    setCopiedDraft(true);
    setTimeout(() => setCopiedDraft(false), 2000);
  };

  return {
    docType,
    setDocType,
    ndaForm,
    setNdaForm,
    noticeForm,
    setNoticeForm,
    isDrafting,
    generatedDraft,
    setGeneratedDraft,
    copiedDraft,
    draftError,
    handleGenerateDraft,
    handleExportPDF,
    handleCopyDraft,
  };
}
